### ISSUE TITLE
Query tag fields

### ISSUE THREAD

**Issue by farcitoast** [RediSearch/JRediSearch#112]
Hi, I need to make a query based on the tag field of an index.
Let's say I create this index:
`FT.CREATE myIndex SCHEMA genre TAG`
Now I add some documents and I need to perform this query:
`FT.SEARCH myIndex "@genre:{ horror | action }"`
or even
`FT.SEARCH myIndex "@genre:{ horror } @genre:{ action }"`

How can I perform this query with JRediSearch? I tried to read the documentation and source code, but I still don't know how to achieve this!

**Comment by gkorland** [comment]
```java
Client cl = ...
cl.search(new Query("@genre:{ horror | action }"));
```

**Comment by farcitoast** [comment]
@gkorland thank you so much, I didn't realize I could also pass field queries into the Query constructor!
