### ISSUE TITLE
redis.clients.jedis.exceptions.JedisDataException: No such property

### ISSUE THREAD

**Issue by devcken** [RediSearch/JRediSearch#118]
Hi, JRediSearch

I recently played with JRediSearch, and faced with wierd situation.

I'm trying to implement Spring Batch item reader with JRedisSearch. It first create index with some information. Then read chunked(paginated) data from DB, and add them to Redis with `Client#addDocuments`.

After adding all of data to Redis, it invoke `Client#aggregate` with `groupBy` and `limit`.

Sadly, Redis response with error; _redis.clients.jedis.exceptions.JedisDataException: No such property 'ategoryNo'_.

Real name of the field is `categoryNo`.

The following is a result of FT.INFO.

```
127.0.0.1:6380> FT.INFO myIdx
 1) index_name
 2) myIdx
 3) index_options
 4) (empty array)
 5) fields
 6) 1) 1) id
       2) type
       3) NUMERIC
    2) 1) price
       2) type
       3) NUMERIC
    3) 1) categoryNo
       2) type
       3) NUMERIC
    4) 1) createdDate
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
```

**Comment by gkorland** [comment]
Can you please check the `monitor` and see that is really sent to Redis?

```basg
> redis-cli
> monitor
```

**Comment by gkorland** [comment]
https://github.com/RediSearch/redisearch-go/issues/117
