### ISSUE TITLE
is there a commands.json file for redissearch?

### ISSUE THREAD

**Issue by zcaudate** [RediSearch/JRediSearch#120]
I'm looking for a data file of the commands that can be parsed. Is there one available?

**Comment by gkorland** [comment]
There is no such file, what are you need it for?

**Comment by zcaudate** [comment]
I'm implementing a redis client base on a stripped down version of on https://github.com/ptaoussanis/carmine and https://github.com/wallrat/labs-redis-clojure - both libraries parse the [commands.json](https://github.com/redis/redis-doc/blob/master/commands.json) to generate the actual functions. I'd like to use that approach as well if possible for implementing command sets for redis modules.

**Comment by sazzad16** [comment]
Closed due to inactivity.
