### ISSUE TITLE
How to get all documents with FT.SEARCH?

### ISSUE THREAD

**Issue by farcitoast** [RediSearch/JRediSearch#128]
Hi, I can effectively search some documents with the Client.search(queryString) method. The result is a SearchResult object, with a totalResults property that correctly tells me the total number of results. How can I have all the documents, and not just the first ten or n, in the docs List of the SearchResult object? I would like not to use to use the limit(int, int) method, because I don't know how much results I have and I can't pick a maximum number.
Thank you.

**Comment by gkorland** [comment]
Can you use Integer.MAX_VALUE for the limit?

**Comment by farcitoast** [comment]
I can't because apparently Redis imposes a limit of 1000000 results from Redis. For now I will use a constant set to 1000000, maybe it would cool to add a MAX_RESULTS constant to the library. Thanks for you help!
