### ISSUE TITLE
Could not index geo value

### ISSUE THREAD

**Issue by jamshedazhar** [RediSearch/JRediSearch#13]
While adding document to index with geo data, it generating exception with `Could not index geo value` value.

`
public class RedisClient {

    private static final Logger LOGGER = LogManager.getLogger(RedisClient.class);
    private static final ObjectMapper mapper = new ObjectMapper();
    private static final String INDEX_NAME = "user";
    private static final String REDIS_HOST = "localhost";
    private static final int REDIS_PORT = 6379;

    private final Client client;
    private final Schema schema;

    public RedisClient() {
        client = new Client(INDEX_NAME, REDIS_HOST, REDIS_PORT);
        schema = new Schema()
                .addTextField("CONTEXT",1.0)
                .addTextField("title", 5.0)
                .addTextField("name", 1.0)
                .addGeoField("location");
    }

    public static void main(String[] args) {
        RedisClient redisClient = new RedisClient();
        redisClient.createIndex();
        User user = new User();
        user.setName("name");
        user.setTitle("body");
        user.setLocation(Arrays.asList(123d, 123d));

        @SuppressWarnings("unchecked")
        Map<String, Object> docs = mapper.convertValue(user, Map.class);
        try {

            redisClient.client.addDocument(UUID.randomUUID().toString(),  docs);
        } catch (JedisDataException ex){
            LOGGER.warn(" ex);
        }
        Query query = new Query("context")
                .addFilter(new Query.GeoFilter("location", 123d,123d, 1, Query.GeoFilter.KILOMETERS));

        SearchResult res = redisClient.client.search(query);
        res.docs.stream()
                .map(Document::toString)
                .map( x -> {
                    try {
                        return mapper.readValue(x, Result.class);
                    } catch (IOException e) {
                    }
                    return x;
                })
                .forEach(System.out::println);
    }

    private void createIndex() {
        try {
            client.createIndex(this.schema, Client.IndexOptions.Default());
            LOGGER.info("Index " + INDEX_NAME + " has been created on redis server");
        } catch (JedisDataException ex) {
            LOGGER.warn(ex);
        }
    }
}
`

Above program suppose to work, but whenever I tried to execute it create exception `redis.clients.jedis.exceptions.JedisDataException: Could not index geo value`.

It seems like we can't index geo attribute but i am not sure how to avoid them. Currently  iam using `Client.IndexOptions.Default()` as indexing option which value i can use to get geo location working with redisearch.

**Comment by itamarhaber** [comment]
Hello @realjam,

> `user.setLocation(Arrays.asList(123d, 123d));`

Where on earth is 123,123? ;)

I suspect that if you'd use lat and lon values per the standard (EPSG:900913 / EPSG:3785 / OSGEO:41001), you'd be ok. For your reference:

* Valid longitudes are from -180 to 180 degrees.
* Valid latitudes are from -85.05112878 to 85.05112878 degrees.

**Comment by realjam** [comment]
Thanks for point out. But I tried with valid lat lon(28.6424958, 77.3147564) but no luck still getting the same exception.

`redis.clients.jedis.exceptions.JedisDataException: Could not index geo value
	at redis.clients.jedis.Protocol.processError(Protocol.java:131)
	at redis.clients.jedis.Protocol.process(Protocol.java:165)
	at redis.clients.jedis.Protocol.read(Protocol.java:219)
	at redis.clients.jedis.Connection.readProtocolWithCheckingBroken(Connection.java:309)
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:236)
	at io.redisearch.client.Client.addDocument(Client.java:289)
	at io.redisearch.client.Client.doAddDocument(Client.java:249)
	at io.redisearch.client.Client.addDocument(Client.java:237)
	at io.redisearch.client.Client.addDocument(Client.java:320)`

**Comment by realjam** [comment]
Hi @itamarhaber
Is there any solution to use JredisSearch with Geolocation in Schema? I am still getting exception on this although I don't want to index the geolocation value.

**Comment by team3** [comment]
The standard `GeoCoordinate`'s method `toString()` produces the value "(longitude, latitude)". But redis expects "longitude, latitude" without brackets.
Use your own data type for storing geo coordinates with the overridden `toString()` method.
```
public class ValidGeoCoordinate {
    private double longitude;
    private double latitude;

    // -----

    @Override
    public String toString() {
      return longitude + "," + latitude;
    }
  }
```
