### ISSUE TITLE
Can 1 client use for all the Threads?  Does it thread safe?

### ISSUE THREAD

**Issue by Taymindis** [RediSearch/JRediSearch#140]
I am currently have a design like this 

```java

Client client = new Client(indexName, jedisPool)

```

Can this client handle all the query from multiple threads concurrently? Or i need to instantiate a new client whenever there is a new request?

**Comment by sazzad16** [comment]
**Client is threadsafe** (considering JedisPool, more specifically, GenericObjectPoolConfig of JedisPool is not weirdly configured).

**Comment by Taymindis** [comment]
Thanks for the clarification.
