### ISSUE TITLE
An option to return only certain fields from a search query

### ISSUE THREAD

**Issue by mankerious** [RediSearch/JRediSearch#15]
Hello,

It would be great to have a way to return only certain fields from a search query. Via CLI it works using ‘ft.search index <query> return 2 field1 field2. We can also see a way to do it in the Python api using the “return_fields” method. 
That functionality can come in very handy in the Java client as well.
Thank you.
Marco

**Comment by itamarhaber** [comment]
Hello Marco,

Thanks for the suggestion, we'd gladly merge a PR that implements it ;)

**Comment by gkorland** [comment]
You should use https://oss.redislabs.com/redisearch/Commands/#ftaggregate instead
