### ISSUE TITLE
what does the totalResults of AggregateResult stand for?

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/JRediSearch#178]
when I use AggregationBuilder r = new AggregationBuilder(q).apply(xxx).filter(yyy).limit(0,10), the totalResults is 9, but the results array is empty, why they are inconsistent?

**Comment by sazzad16** [comment]
@chenlizhao What do you see when you query from other client, i.e. `redis-cli`.

**Comment by gkorland** [comment]
ref https://github.com/RediSearch/RediSearch/issues/2497

**Comment by chenlizhao** [comment]
> @chenlizhao What do you see when you query from other client, i.e. `redis-cli`.

it is not related with java cilent, sorry for that!
