### ISSUE TITLE
Java client API supporting Redisearch

### ISSUE THREAD

**Issue by chaitradalawai** [RediSearch/JRediSearch#187]
I have been using Redisearch through JRedisearch API in my project. I recently got to know this API is deprecated. It would be really helpful if you could provide the alternative API and links for examples if published any.

**Comment by sazzad16** [comment]
JRediSearch is deprecated in favor of [Jedis](https://github.com/redis/jedis/). There's a [quick start](https://github.com/redis/jedis/blob/master/docs/redisearch.md) guide. More example can be found in [search tests](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/modules/search/SearchTest.java) and [aggregation tests](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/modules/search/AggregationBuilderTest.java).

PS: @chaitradalawai Where have you found the information for deprecation? Asking because same doc should also contain the reference to Jedis.

**Comment by sazzad16** [comment]
0. If you notice, the full sentence says "Please notice JRediSearch is deprecated and you should use Jedis 4.2 which has built in support for RediSearch."
1. Never.
  But its development is stopped. So there won't be any update (until and unless the decision is reverted).
2. You can check dependencies of Jedis [4.2.3](https://mvnrepository.com/artifact/redis.clients/jedis/4.2.3) [here](https://mvnrepository.com/artifact/redis.clients/jedis/4.2.3).
3. I can't promise anything. It's development.
  But such major change is *unlikely* to happen in near future.
4. That's cluster mode. You're not supposed to use it if don't know what it is.

**Comment by chaitradalawai** [comment]
Thanks for the clarification.

**Comment by chaitradalawai** [comment]
Hi,
I was using the below code to create client object with host port and index names, I think the Client object has to be replaced with JedisPooled in Jedis approach, could you please tell which syntax to use to pass password arg ?

io.redisearch.client.Client.Client(String indexName, String host, int port, int timeout, int poolSize, String password)

**Comment by chaitradalawai** [comment]
And also please tell about the corresponding jedis for the below JRedisearch code

1.  is there any similar method for the Client object creation to access Redis( above question) ----- io.redisearch.client.Client.Client(String indexName, String host, int port, int timeout, int poolSize, String password) ?

2. I am dropping the index and recreating it on scheduled basis using the method (client.dropIndex(true) - missingOk If the index does not exist, don't throw an exception instead return false), where it doesn't throw exception even if the index doesn't exist, if I use the "redis.clients.jedis.UnifiedJedis.ftDropIndexDD(String indexName)"  it gives the following exception when loading data for the first time  (redis.clients.jedis.exceptions.JedisDataException: Unknown Index name )----------- I am doing this operation since there is no functionality to remove all the docs from the index. Is there any method which deletes all the records from an index or check if an index is existing already for supporting removing and reloading all the data on scheduled basis?

3.  I am using the following code to load all the documents by replacing the old ones with new io.redisearch.client.Client.addDocument(String docId, double score, Map<String, Object> fields, boolean noSave, boolean replace, byte[] payload) ----------- is there any similar method in Jedis to replace existing docs with new ones ?

**Comment by sazzad16** [comment]
@chaitradalawai 

1. Not directly. You may provide `GenericObjectPoolConfig<Connection>` for the `poolSize`.

```
GenericObjectPoolConfig<Connection> config = new ConnectionPoolConfig();
config.setMaxTotal(poolSize);

UnifiedJedis client = new JedisPooled(config, host, port, timeout, password);
```

2. No.

You may consider following:

```
public static boolean safeFtDropIndexDD(UnifiedJedis jedis, String indexName) throws JedisException {
  try {
    return "OK".equals(jedis.ftDropIndexDD(indexName));
  } catch (JedisDataException jde) {
    if (jde.getMessage().toLowerCase().contains("unknown")) {
      return false;
    }
    throw jde;
  }
}
```

3. Document has been removed/deprecated from RediSearch. You can either use HASH or JSON data structure.

**Comment by chaitradalawai** [comment]
Hi,

About 3rd question, 
I am using the following code to load all the documents by replacing the old ones with new io.redisearch.client.Client.addDocument(String docId, double score, Map<String, Object> fields, boolean noSave, boolean replace, byte[] payload) ----------- is there any similar method in Jedis to replace existing docs with new ones ?

1. I see the document in jedis implementation "redis.clients.jedis.search.Document", is this deprecated too ?
2. I want to refresh my cache data by replacing old value with new ones, which was supported through above mentioned method in JRedisearch, is there a similar approach in Jedis ? 
I see "hset" is there in Jedis for adding a new document, does this also replace if given the same key ? (i.e. key = Index_prefix:unique_id )

**Comment by sazzad16** [comment]
1. "redis.clients.jedis.search.Document" is not deprecated (yet).
2. Yes; existing fields will be replaced and new fields will be added.

**Comment by sazzad16** [comment]
**At this moment,** there is no such plan.

**Comment by chaitradalawai** [comment]
thanks for all the answers :)
