### ISSUE TITLE
AggregationRequest issues

### ISSUE THREAD

**Issue by dme-development** [RediSearch/JRediSearch#36]
In followup of the aggregation range suggestion by Kyle Davis on the RediSearch forum: https://groups.google.com/forum/#!topic/redisearch/QLECmLcDxgk
there are two issues with the AggregationRequest:

Issue 1:
To my opinion the api executing order should follow the order of the way it is constructed.

Eg:
```
new AggregationRequest(query)
.apply("projection", "alias1")
.apply("projection", "alias2")
.groupBy("@alias2", Reducers.count().as("alias3"))
```
Now this is not the case. GROUPBY is always set in the execute message before APPLY.

Issue 2:
Also in AggregationRequest.cs in the serializeRedisArgs method, I believe the rule
```
args.add("APPLY");
```
should be inside the for loop
```
for (Map.Entry<String, String> e : projections.entrySet()) {
```
in case you want to use multple APPLY actions, like in the example above.

**Comment by manojjayaraman** [comment]
I have submitted a PR  to support projection on query(issue 1) in addition to apply after grouping as redisearch supports both. Also introduced support for FILTER after grouping.

I addition also moved args.add("APPLY") inside the loop for the existing apply.

**Comment by gkorland** [comment]
An AggregationBuilder was introduced to replace AggregationRequest
