### ISSUE TITLE
why not running Jredisearch???

### ISSUE THREAD

**Issue by jeetkn** [RediSearch/JRediSearch#51]
```java
package redisTest;

import io.redisearch.client.Client;
import io.redisearch.Document;
import io.redisearch.SearchResult;
import io.redisearch.Query;
import io.redisearch.Schema;

public class redisearchTest {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Client client = new Client("user", "211.239.124.227",6379);	
	}
}
```

```
Exception in thread "main" java.lang.NoClassDefFoundError: redis/clients/jedis/util/Pool
	at redisTest.redisearchTest.main(redisearchTest.java:13)
Caused by: java.lang.ClassNotFoundException: redis.clients.jedis.util.Pool
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
I am using it with Jedis2.9.0.
my redis version 4.9.106 and jredisearch version 0.22.0
Jedis is works well 
I dont know why not running this code.
my java version is 1.8

**Comment by gkorland** [comment]
0.22.0 is dependent on jedis 3.0.x

**Comment by shannonantony** [comment]
when I use jedis 3.0, i am getting JVM error while using RedisTemplate from Spring Data Redis. can you please take a look. thanks,

**Comment by gkorland** [comment]
The thing is that Spring Data Redis is defendant on Jedis 2.9 can you try spring-data-reids:2.2.0.M3?

**Comment by shannonantony** [comment]
I tried 2.2.0.M3, but i get other issues. Is there any plans to make Jedis to work with latest version of spring-data-redis? thanks

**Comment by gkorland** [comment]
>I tried 2.2.0.M3, but i get other issues.
What are the other issues you got?

>Is there any plans to make Jedis to work with latest version of spring-data-redis?
We can't really, since spring-data-redis is already coming with a pre defined jedis@2.9

**Comment by sazzad16** [comment]
Closed due to inactivity.
