### ISSUE TITLE
Retrieve multiple documents based on docIds similar to FT.MGET

### ISSUE THREAD

**Issue by shannonantony** [RediSearch/JRediSearch#59]
I would like to know how do I retrieve multiple documents by passing list of docIds similar to FT.MGET funcitonality

**Comment by mnunberg** [comment]
@gkorland @shannonantony do you want to have a java API for MGET?

**Comment by shannonantony** [comment]
Yes please. sorry if I didn't explain correctly

**Comment by shannonantony** [comment]
@mnunberg will you be able to add java api for MGET? thanks

**Comment by shannonantony** [comment]
thank you @gkorland
