### ISSUE TITLE
Add Client constructor using existing JedisPool + password auth

### ISSUE THREAD

**Issue by fcerbell** [RediSearch/JRediSearch#61]
There is a Client constructor method using and existing JedisPool, but without possibility to give a connection password.

My current workaround is to use the constructor with host/port, but it creates another JedisPool.

**Comment by gkorland** [comment]
@fcerbell I'm not sure I follow, why can't you create the Jedis pool with password?

**Comment by fcerbell** [comment]
Le 2019-03-10 08:58, Guy Korland a écrit :
> @fcerbell [1] I'm not sure I follow, why can't you create the Jedis
> pool with password?
>

@gkorland because I missed this method signature with password in Jedis 
API. I manually sent AUTH with Jedis for the 2 last years... I have to 
update all my code ;)

Sorry. This issue is irrelevant. Can be closed

Regards
François
