### ISSUE TITLE
Class conflicts while using JRediSearch with SpringDataRedis RedisTemplate

### ISSUE THREAD

**Issue by shannonantony** [RediSearch/JRediSearch#62]
I am facing class conflict issue while using JRediSearch with SpringDataRedis RedisTemplate in the same SpringBoot application.

**Comment by gkorland** [comment]
Please verify both are using Jedis 3.0.x

**Comment by shannonantony** [comment]
Tried with Jedis 3.1.0 and spring-boot-starter ver. 2.1.3.RELEASE

I get following JVM error while autowiring StringRedisTemplate

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000051b88a83, pid=47680, tid=34676
#
# JRE version: Java(TM) SE Runtime Environment (8.0_20-b26) (build 1.8.0_20-b26)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.20-b23 mixed mode windows-amd64 compressed oops)

**Comment by gkorland** [comment]
Can you please try with the latest spring-data-redis milestone? 
https://github.com/spring-projects/spring-data-redis/releases/tag/2.2.0.M3

**Comment by gkorland** [comment]
duplicate #51
