### ISSUE TITLE
Schema.TagField is not SORTABLE

### ISSUE THREAD

**Issue by rnbWarden** [RediSearch/JRediSearch#64]
Is there a reason TagField does not expose a sortable constructor. It's hard-coded to false.

If not I'm happy to supply a PR for it, but wanted to ask before doing so. It appears the Lettusearch client provides for it and it looks like it should be allowed based on the documentation.

Also any plans to provide support for FT.ALTER to allow the previously created fields to be set as sortable? Lettusearch also provides this functionality which is especially useful in cases like this.

**Comment by gkorland** [comment]
No reason not support it, I'll be glad to merge a PR

**Comment by rnbWarden** [comment]
now that we have merged the PR for the constructor, can we get a release for it?

Also would like you input on FT.ALTER support.

**Comment by gkorland** [comment]
#69 opened an issue for F>ALTER

**Comment by rnbWarden** [comment]
@gkorland - how about a Release which includes support? I don't want to run off a snapshot if possible.

**Comment by gkorland** [comment]
We just released v1.0.0-rc3 and plan to release v1.0.0 this week
