### ISSUE TITLE
Implement Cursor API support

### ISSUE THREAD

**Issue by rnbWarden** [RediSearch/JRediSearch#66]
missing support for the Cursor API (WITHCURSOR) on AggregationRequest (FT.AGGREGATE)

**Comment by gkorland** [comment]
@rnbWarden thanks for the feature request, if you have a ready to merge PR we'll be glad to merge it.

**Comment by rnbWarden** [comment]
I don't have a PR for this currently. I may get to it in time but have been busy creating another project which serves as a JPA-like abstraction on top of both the Jedis and Lettuce search clients giving CRUD access in a spring-data like manner. That is my main focus and as I'm implementing functionality from the Lettuce side I'm finding a few features lacking in the JRediSearch support.
