### ISSUE TITLE
AggregationResult to include `totalResults` like SearchResult

### ISSUE THREAD

**Issue by timmixell** [RediSearch/JRediSearch#80]
SearchResult currently returns the `totalResults` of a [query](https://github.com/RediSearch/JRediSearch/blob/master/src/main/java/io/redisearch/SearchResult.java#L42), while AggregationResult does not appear to. 

It would be nice to have functional parity, unless there's a compelling reason it was omitted? I can submit a PR, if this request is acceptable.

Thanks!

**Comment by gkorland** [comment]
@timmixell thanks for the comment, if you can submit a PR that will be great
