### ISSUE TITLE
Cannot initialize GeoValue

### ISSUE THREAD

**Issue by angelo147** [RediSearch/JRediSearch#86]
Trying to initialize a GeoValue using its contructor, i came up with the problem that GeoValue.Unit enum is not public and is needed as an argument. Also in the Values class there isnt any method to provide a GeoValue.
Am i something missing about how to create a new GeoValue or is it a bug?

**Comment by gkorland** [comment]
@angelo147 you're right thanks! it seems like since the test are on the same package they didn't fail.
I'll push a fix right away.
