### ISSUE TITLE
SSL connection

### ISSUE THREAD

**Issue by angelo147** [RediSearch/JRediSearch#88]
Hello,
Its not a bug but more a question. How can a establish a SSL connection using JRedisearch client?

**Comment by gkorland** [comment]
@angelo147 please notice one one of the Client constructors can get a Jedis pool.
https://www.javadoc.io/doc/com.redislabs/jredisearch/latest/io/redisearch/client/Client.html

Using this constructor you can pass a jedis pool that is using SSL connection.

**Comment by angelo147** [comment]
Thank you for your answer.
