### ISSUE TITLE
NPE when a document field is null

### ISSUE THREAD

**Issue by tgrall** [RediSearch/JRediSearch#91]
With the following schema:

```java
       Schema sc = new Schema()
                .addTextField("title", 1.0)
                .addTextField("genre", 1.0)
                .addTextField("plot", 1.0)
                .addSortableNumericField("release_year")
                .addTagField("tag")
                .addGeoField("loc");
```
when I try to insert some field with a null value it raises a NullPointerException

```
       fields = new HashMap<>();
        fields.put("title", "another title another test");
        fields.put("genre", "Action");
        fields.put("plot", null);
        fields.put("tag", null);
```

**Proposal**

* Set the null values to `""` empty String.
* When the type is not a String for example `GeoField` or `Numerical` it will raise an clear exception

I have implemented in Document using a simple stream collector

```
        // replace empty value with an empty string
        this.properties = fields.entrySet()
                .stream()
                .map(e -> {
                    if (e.getValue() == null)
                        e.setValue("");
                    return e;
                })
                .collect(Collectors.toMap(
                        Map.Entry::getKey,
                        Map.Entry::getValue)
                );
```

BUT:
* this breaks some test since many test are using Strings comparison, and this loop is changing the order of the field (I have not identified the exact source so far)
   * see [here](https://github.com/RediSearch/JRediSearch/blob/e6cd28e30192a1f687770416b36f5f19dc5dcbd1/src/test/java/io/redisearch/client/ClientTest.java#L68)

*Questions:*

* Are you ok with the proposal? 
   * another option will be to remove the empty fields, but they will not appears in the doc

* Should I "find a way to keep" the String comparison? (not sure it is a good idea)
* or find a way to do some more canonical test?
   * for example testing substring find `"title"="hello world"` and other attributes for example

**Comment by gkorland** [comment]
> another option will be to remove the empty fields, but they will not appears in the doc
I  think this is the right solution
