### ISSUE TITLE
Problem with RangeValue support only double values

### ISSUE THREAD

**Issue by angelo147** [RediSearch/JRediSearch#93]
Trying to query on an epoch timestamp i get a server error.
For example:
Values.gt(1587058030).toString() produces this [(1.58705803E9 inf]
resulting to the following error from the server when executing search
Exception in thread "main" redis.clients.jedis.exceptions.JedisDataException: Syntax error at offset 20 near E9

**Comment by angelo147** [comment]
I dont know if this is the right approach but after playing a little with FT.EXPLAIN and numeric ranges, I found out that replacing `Double.toString(n)` in appendNum() with `new BigDecimal(n).setScale(6, RoundingMode.HALF_EVEN).toPlainString()` produced the same numeric values and my quries worked as expected.

**Comment by gkorland** [comment]
@angelo147 please see draft PR #96 the idea is to handle keep Long as long and not convert to double.
It doesn't fix the parsing issue on the server that should be able to handle ranges with `1.58705803E9` but it keeps the accurate value and provide a solution for your use case.

**Comment by angelo147** [comment]
@gkorland thanks, that seems to work for epoch timestamps and for sure is a more complete approach. But seems that i have to wait for a RediSearch fix for an actual support of long and double types so i will stick to my custom solution till then.
